### ISSUE TITLE
Question: Open Box Sides and Elastic shapes

### ISSUE THREAD

**Issue by tajmone** [ascii-boxes/boxes#25]
In the docs it says:

> * At least one shape per side must be elastic.
 
But if a box has and open side (lets say the right one), then why would the top and bottom side need be elastic at all? Couldn't it be a fixed design, wrapping the text above, left, below, without closing it on the left. So, there would be no real need for elastic sides, except on the right, which would have to stretch to accomodate the number of text lines. 

The top and bottom could consist just of a N and S fixed designs. And right could just be an elastic W (eg: " || "). No corners needed either. It would be like a kind of "C" design, that clamps part of the text horizontally, and doesn't care if the text is longer than the top edge.

Is this allowed right now?

**Comment by tsjensen** [comment]
You are right, and the effects you describe are possible and supported.

However, in order to keep things simpler, box sides can either be *open* or *not open*. If not open, they must contain at least 1 elastic shape. If open, they must not contain any shapes (or only shapes made out of spaces).

So, in your example, the top and bottom sides would not be open, and thus must contain at least 1 elastic shape. That shape may consist entirely of spaces, rendering it "invisible". The definition of the elastic shape is needed, because it is the only way for *boxes* to know whether you want the space to the right or to the left of the **N** and **S** shapes to be considered elastic.

**Comment by tajmone** [comment]
Rightly so, but the open side would not have any elastic element, right? (in the example above, the right side).
But I see your point, an elastic side is needed, even if empty. Didn't think of that.

**Comment by tsjensen** [comment]
Right. In the config file, open sides do not contain any shapes, so they also do not contain elastic shapes.

**Comment by tsjensen** [comment]
Hi @tajmone, did I answer your question? If so, it would be great if you closed this issue. If not, please go on. Thanks!

**Comment by tajmone** [comment]
Yes, it did clear out most doubts. Sorry for the delay. I was just trying to figure out the exact ramifications of the isse, for the GUI fronted project I had in mind. But I guess that the best approach would be thoroughly testing it out myself, and see what error messages I get from boxes when I missing something out — As well as peeking in the source code, obviously.

Ok, I'll close the issue. If i have further questions I'll just email you. Anyhow the GUI project will have to wait that I finish and deliver a translation job I am working on, after which I'll have lot of spare time
