### ISSUE TITLE
Allow alias names for designs

### ISSUE THREAD

**Issue by kiryph** [ascii-boxes/boxes#30]
I would like to make your vim-integration more flexible. Instead of defining for every filetype an autocommand, I would prefer to sync design names and filetype names of vim, so there is an autocommand using the filetype option of vim.

Adding a second design name, e.g. to `ada-box` the alias `ada` and to `shell` the alias `Makefile`, `makefile` etc, would be necessary.

**Comment by tsjensen** [comment]
This should not be too difficult. I suppose all aliases must be unique.

**Comment by mathomp4** [comment]
I have an extra vote for this for a couple of reasons.

First, I was about to make a PR to include things like `lua-box` and `lua-cmt` but guess what? [Lua](https://www.lua.org/pil/1.3.html) uses the same `--` comment character as [Ada](https://www.adaic.org/resources/add_content/standards/05rm/html/RM-2-7.html)! I mean, I guess I could "duplicate" the code, but that seems wasteful. So if we could do:
```
BOX ada-cmt lua-cmt
```
and:
```
BOX ada-box lua-box
```
that would be useful.

Second, I'm a Fortran programmer and as such use `f90-box` a lot. But, in truth, I'd probably prefer to just type `boxes -d fortran` instead because I don't deal with FORTRAN 77 much, so I don't need to care about that too often.  So if I could have:
```
BOX f90-box fortran
```
that'd please me greatly!

**Comment by tsjensen** [comment]
Totally agree, this would be quite useful. I'll do my very best!

**Comment by mdebusk** [comment]
> First, I was about to make a PR to include things like `lua-box` and `lua-cmt` but guess what? [Lua](https://www.lua.org/pil/1.3.html) uses the same `--` comment character as [Ada](https://www.adaic.org/resources/add_content/standards/05rm/html/RM-2-7.html)!

SQL uses the same style too.

**Comment by tsjensen** [comment]
We will need a special keyword for this. I think

    BOX ada-cmt alias (lua-cmt, sql-cmt)

**Comment by tsjensen** [comment]
Done. This will be in *boxes* v2.1.0. ✔️

The syntax turned out to be just commas, so you can now `BOX main_name, alias1, alias2`, but you only `END main_name`.

Code for the already completed new features is collected on the [rc_2.1.0](https://github.com/ascii-boxes/boxes/tree/rc_2.1.0) branch, in case you want to have a look, or try them out early.
