### ISSUE TITLE
Change default "carriage return" 

### ISSUE THREAD

**Issue by drazde** [ascii-boxes/boxes#48]
Hi, 
I would like the default "carriage return", for use or CR or LF or both
 I don't find any parameter to do that.

To avoid this (on windows). 
PS: I use mainly sublime

![immagine](https://user-images.githubusercontent.com/2643448/40480104-c78f0256-5f4d-11e8-8e2e-44a7654871f7.png)

![immagine](https://user-images.githubusercontent.com/2643448/40480185-fd863654-5f4d-11e8-887b-6d0f8c7c08a4.png)

**Comment by tsjensen** [comment]
Thank you for this!
It requires a tiny bit of digging on my part, which I'll have time to do on the weekend. I'll report back here.

**Comment by tsjensen** [comment]
Well, had some time today. 😄 
This actually seems to be a FilterPipes issue. When boxes is called on the command line, the line endings are correct. FilterPipes, however, adds an extra CR, so that we get CR-CR-LF. This has nothing to do with boxes, and happens with completely different filters, too.
So, I'm afraid you'll have to open this issue with [FilterPipes](https://github.com/tylerl/FilterPipes/issues) instead.

**Comment by drazde** [comment]
Ok, sorry for my wrong reporting.
I open a issue on [FilterPipes](https://github.com/tylerl/FilterPipes)

**Comment by tsjensen** [comment]
> Ok, sorry for my wrong reporting.

No problem, this was not clear to me either, until I looked at it much more closely. 😄

**Comment by tsjensen** [comment]
By the way, just in case FilterPipes didn't get fixed: Since v2.1.0, boxes has an option `-e` to change the line break. 😊
