### ISSUE TITLE
"Toggle" function when commenting code with Notepad++

### ISSUE THREAD

**Issue by pidgeon777** [ascii-boxes/boxes#58]
In Notepad++, when you want to toggle some code comments you can press `Ctrl + Q`.

Pressing that combination adds comments if absent, else removes them:

![rglaktsgc8](https://user-images.githubusercontent.com/13739892/52648392-becd6b80-2ee6-11e9-8d03-627a79b74bd1.gif)

Do you think that something like that could be doable with Boxes? I mean, an option so that:
- If the selection has been previously commented, then Boxes removes the comments.
- If the selection is not commented, then Boxes add the comments.

This could also apply to the other Boxes block templates as well (i.e., not related to code comments).

So, something like this:
- If Boxes has not been applied to the selection, then enclose the text with Boxes:
`boxes -d <BOX_DESIGN> "$(ascfile)" "$(tempfile)"`
- If the selection has been processed with Boxes, then remove text added by Boxes:
`boxes -r -d <BOX_DESIGN> "$(ascfile)" "$(tempfile)"`

Thus, the resulting command could be something like the following:

`boxes -toggle -d <BOX_DESIGN> "$(ascfile)" "$(tempfile)"`

where `toggle` could represent the newly added option.

**Comment by tsjensen** [comment]
Thank you for the suggestion! It certainly seems quite useful to have, as you'd have only one "toggle" hotkey to memorize instead of two. Also, some IDEs have keys like that.

Still, I'm afraid we can't do it.

*boxes* is a fairly generic kind of program, for adding all kinds of boxes. We obviously can't have features that work only with a subset of boxes, as that would be very confusing. How should the casual *boxes* user be able to tell which features work with which box designs?

The difficulty is finding out reliably whether the box has already been applied. Trust me, there are too many cases which just don't work. For line comments, it would be no big problem, like you showed. But it *would* still be a problem, for example when only some of the selected lines have comments. This happens when you're commenting out a section of code that already has a regular line comment. Contrary to an IDE, *boxes* has no state, so it can't know if it has been invoked before on the same lines.

So such a function can't be implemented reliably and would draw lots of questions by users who don't get the expected behavior.

**Comment by pidgeon777** [comment]
I understand, thank you. So at this point, I think it would be enough to assign some shortcuts in Notepad++ as follows:
- Ctrl + <X>: Add boxes.
- Ctrl + <Y>: Remove boxes.

At first, I thought that by making use of the autodetect box function (already implemented in Boxes by scanning the whole config file), my suggestion could be feasible.
