### ISSUE TITLE
Support For ANSI/VT100 Control Sequences

### ISSUE THREAD

**Issue by matteoguglielmi** [ascii-boxes/boxes#65]
I'm using boxes 1.3 on a linux box.

It would be wonderful to have full support for "colors" such as:

`echo -e '\e[41mHELLO\e[49m\n\e[41mWORLD\e[49m' | ./boxes -f boxes-config -d shell -s 50 -a hcvc`

Currently the colors are reproduced correctly but the boxes are drawn incorrectly due to the presence of the escape sequences:

```
##################################################
#                HELLO                 #
#                WORLD                 #
##################################################
```

Since I truly love to have colored text, is anybody willing to tell me where in the source code I should take a look to come up with a quick and dirty fix for this specific case (2 escape sequences of the same length per line, on all lines)?

**Comment by tsjensen** [comment]
Hey @matteoguglielmi - thank's for sharing this idea! I must admit, I would like that, too. 😊  
Like you noticed, it's not currently possible, because *boxes* doesn't know the correct line lengths with all the escapes in them.

This would be somewhat of a difficult change, as you would have to reliably detect all the escape sequences, which will probably require a library to do right. Which leads us to a better build system, for instance with cmake (tried on one of the branches). Then you could run the regular code with a "normal" string, and at the end, output the text with escapes again. A problem will be that *boxes* runs on a lot of platforms (more than 20, as far as I know), some of which will have different escape sequences ... So all in all, quite a tough task, even for a veteran.

I'll leave this open as an enhancement request. Who knows? And if you'd like to tackle it, that'd be great!

Until it gets implemented, you can at least add the colors later, like meyer did here: #13

**Comment by tsjensen** [comment]
Probably relates to #49

**Comment by matteoguglielmi** [comment]
Thanks for this patch!

For what I need, it works just fine!
