### ISSUE TITLE
Spec file for building RPMs

### ISSUE THREAD

**Issue by dvmc** [ascii-boxes/boxes#76]
I have been trying to use the `boxes.spec` file to build an RPM. First, I had to do some adjustments (change `copyright` to `license`, and properly escape the `%` in the find command by doubling it). This is the command that I tried after building boxes:

    rpmbuild -ba boxes.spec --build-in-place

This is as far as I could get. Now I get the following error:

    Bad file: /home/d2/rpmbuild/SOURCES/v2.0.0.tar.gz: No such file or directory

I'm not too familiar with the RPM building process, so I don't know if the spec file needs further adjustments, or if it is just an invocation problem on my end.

**Comment by tsjensen** [comment]
Ah, well, the boxes.spec file is something I should remove from the repo, probably. I actually used it to build an RPM package 20 years ago, but that's not very useful today.

In order to help you, maybe [this spec file](https://atim.fedorapeople.org/for-review/boxes.spec) by @tim77 is a better starting point for you. @tim77 uses it to build the official [*boxes* package](https://koji.fedoraproject.org/koji/buildinfo?buildID=1711564) for Fedora, which is also RPM-based.

**Comment by dvmc** [comment]
Thanks for the pointer! I can confirm that I can't compile Tim's spec file either, so it is definitely an invocation issue on my side.

**Comment by tim77** [comment]
Latest .spec file for Fedora [here](https://src.fedoraproject.org/rpms/boxes/blob/rawhide/f/boxes.spec). JFYI.
