### ISSUE TITLE
Allow blank boxes when specified via `-c " "`

### ISSUE THREAD

**Issue by tsjensen** [ascii-boxes/boxes#88]
The discussion in #86 showed that it may make sense to allow boxes consisting entirely of spaces. Then *boxes* could be used for aligning blocks of text, or previously drawn boxes, within a terminal window.

Currently, blank boxes are explicitly forbidden. We should find out why that is, and consider allowing them again, or document the reason why it can't be allowed.

**Comment by Davidy22** [comment]
So I went into the code and commented this little check out:

`
    /*
     *  At least one shape must be specified
     */
    if (bison_args->num_shapespec < 1) {
        yyerror(bison_args, "must specify at least one non-empty shape per design");
        return RC_ERROR;
    }`

At line 469 in parsecode.c. Then I subbed the full width space I was using earlier with an ASCII space and the centering works great. Doesn't fail extra tests when I commented the line out either. Was there a reason for the check? Because from what I can tell it only stops us from making all-whitespace boxes that are kind of useful, and there's an additional check for completely empty boxes to stop whatever bounds errors at zero there might be. I also commented out the whole else half of command_line_design, line 227 in cmdline.c

`static int command_line_design(opt_t *result, char *optarg)
{
    result->cld = (char *) strdup(optarg);
    if (result->cld == NULL) {
        perror(PROJECT);
        return 1;
    }
    else {
        line_t templine = {0};
        templine.len = strlen(result->cld);
        templine.text = result->cld;
        if (empty_line(&templine)) {
            fprintf(stderr, "%s: boxes may not consist entirely of whitespace\n", PROJECT);
            return 1;
        }
    }
    result->design_choice_by_user = 1;
    return 0;
}`

And this also passes tests, makes -c " " work, and I can't make it do anything weird and unexpected.

**Comment by tsjensen** [comment]
Thanks for the analysis. But let me have a look, too.  
Unfortunately, our tests are not very detailed. They are all black-box tests and we have nothing resembling actual unit tests. So the fact that the tests pass would only mean that we have no really big problems ...

**Comment by tsjensen** [comment]
First finding: It seems blank boxes are problematic for the design auto-detector which is used when removing or mending boxes. A blank box is indistinguishable from a broken part of the box or even a missing box, especially on the east side. → Maybe we can allow blank boxes only if specified via `-c`, then the design auto-detector wouldn't encounter them ...

**Comment by tsjensen** [comment]
Ok, I completed the reasearch. We can have blank boxes via `-c`, but not in the config file. I believe this should cover your use case.

**Comment by Davidy22** [comment]
Yeah that'll do it. Can close this with a commit cutting the check then, unless there was anything else that needed to be added to make it work
